### PR TITLE
Update WMUsedRootCAs.cer

### PR DESCRIPTION
**Pull request by colmer**
Add new Webmoney certificate.

---
This change is [Reviewable](https://reviewable.io/reviews/baibaratsky/php-webmoney/107)

### CODE REVIEW

**Comment by baibaratsky** [comment]
Please provide a proof link to the official resource. I have to know that the certificate is genuine. Thank you!

**Comment by colmer** [comment]
https://wiki.wmtransfer.com/projects/webmoney/wiki/WebMoney_root_certificate
It's new certificate. Watch in (in PEM format for use with the CURL library, etc.).

**Comment by baibaratsky** [comment]
I‘ve found there only a certificate that‘s already in this repository. Can‘t find one you want to be added.

**Comment by colmer** [comment]
Sorry, is's was a w3s.webmoney.ru new certificate. They change it at 5 a.m., and root certificate is not working. But  new cert w3s.webmoney.ru work fine. I think now they fix that.

**Pull request closed without merging**
